apiVersion: v1
kind: Service
metadata:
  name: keydb-service
  namespace: food-delivery
  labels:
    app: food-delivery
    component: keydb
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: keydb
  selector:
    app: food-delivery
    component: keydb
