apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-delivery.fullname" . }}-kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: broker
    - port: 29092
      targetPort: 29092
      protocol: TCP
      name: internal
  selector:
    {{- include "food-delivery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
