apiVersion: v1
kind: Secret
metadata:
  name: {{ include "food-delivery.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-delivery.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
  STRIPE_API_KEY: {{ .Values.secrets.STRIPE_API_KEY }}
  GOOGLE_MAPS_API_KEY: {{ .Values.secrets.GOOGLE_MAPS_API_KEY }}
  MAIL_PASSWORD: {{ .Values.secrets.MAIL_PASSWORD }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD }}
