apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-delivery.fullname" . }}-zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "food-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.zookeeper.clientPort }}
      targetPort: {{ .Values.zookeeper.clientPort }}
      protocol: TCP
      name: client
  selector:
    {{- include "food-delivery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
